---
apiVersion: v1
kind: Namespace
metadata:
  name: gosmee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee
  namespace: gosmee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: ghcr.io/chmouel/gosmee:main
          imagePullPolicy: Always
          name: gosmee
          foo
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/kOia9PG8xXmnoNsZ",
              "http://pipelines-as-code-controller.pipelines-as-code:8080",
            ]
