apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-from-remote
  annotations:
    pipelinesascode.tekton.dev/task: "./task.yaml"
spec:
  tasks:
    - name: say-hello
      taskRef:
        name: hello
