apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: remote-task
spec:
  params:
    - name: foo
      type: string
  steps:
    - name: echo
      image: alpine
      script: |
        echo Foo has been set to $(params.foo)
        exit 1
