---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: update-branch-git
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^g"
spec:
  pipelineSpec:
    tasks:
      - name: update-branch
        displayName: Update pull request with main
        taskSpec:
          steps:
            - name: update
              image: cgr.dev/chainguard/git:latest
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "{{ git_auth_secret }}"
                      key: "git-provider-token"
              script: |
                set -x
                cd /tmp
                git clone https://git:$GITHUB_TOKEN@github.com/{{ sender }}/{{ repo_name }}/ -b  {{ source_branch }}
                cd {{ repo_name }}
                git config --global user.email "pac@pipelinesascode.com"
                git config --global user.name "PipelinesAsCode"
                git remote add upstream https://git:$GITHUB_TOKEN@github.com/{{ repo_owner }}/{{ repo_name }}/ 
                git fetch -a upstream
                git rebase upstream/main
                git push origin HEAD:{{ source_branch }} --force-with-lease
