---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: implicit
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "1"
    pipelinesascode.tekton.dev/on-comment: "^/hello$"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
      - name: cache
    tasks:
      - name: task
        displayName: checkout build and test
        workspaces:
          - name: source
            workspace: source
          - name: cache
            workspace: cache
        taskSpec:
          workspaces:
            - name: source
            - name: cache
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo {{ event_type }}
  workspaces:
    - name: source
      emptyDir: {}
    - name: cache
      emptyDir: {}
