---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: jira
  pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/chmouel/pipelinerun-jira-pullrequest/main/tekton/jira.yaml"
  pipelinesascode.tekton.dev/on-comment: "^/jira"
  pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  pipelineRef:
    name: create-jira-from-pr
  params:
    - name: PR_URL
      value: "{{ repo_url }}/pull/{{ pull_request_number }}"
    - name: GITHUB_TOKEN_SECRET
      value: "{{ git_auth_secret }}"
    - name: GITHUB_TOKEN_KEY
      value: "secret"
    - name: AI_TOKEN_SECRET
      value: "gemini"
    - name: AI_TOKEN_KEY
      value: "secret"
    - name: JIRA_TOKEN_KEY
      value: "jira"
    - name: JIRA_TOKEN_SECRET
      value: "secret"
    - name: JIRA_USER_EMAIL
      value: "cboudjna@redhat.com"
    - name: JIRA_PROJECT
      value: "TP"
    - name: JIRA_TEXT
      value: "{{ trigger_comment }}"
