---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: noop
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: main
    pipelinesascode.tekton.dev/on-event: pull_request
  description: |
    This PipelineRun is used to trigger a no-op task when a pull request is opened or updated.
    It does not perform any actions but serves as a placeholder to ensure the pipeline runs.
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                exit 0
