---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: demo
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: main
    pipelinesascode.tekton.dev/on-event: pull_request
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: python:3.12-alpine
              resources:
                limits:
                  memory: 64Mi
              script: |
                #!/usr/bin/env python3
                chunks = []
                chunk_size = 8 * 1024 * 1024
                i = 0

                print("Allocating memory until the container is OOM-killed...")
                while True:
                    chunks.append(bytearray(chunk_size))
                    i += 1
                    print(f"allocated ~= {i * 8} MiB", flush=True)
