---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: on-comment-test
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/on-comment: "/make-me-a-sandwich"
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo '{{ revision }}'
                echo '{{ hello }}'
                exit 0
