---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repo_url
    - name: revision
      default: main
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
    # Customize this task if you like, or just do a taskRef
    # to one of the hub task.
    - name: noop-task
      displayName: Task with no effect
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: noop-task
            image: registry.access.redhat.com/ubi9/ubi-micro
            workingDir: $(workspaces.source.path)
            script: |
              exit 0
