---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pullrequest-{{repo_name}}-{{repo_name}}
spec:
  #workspaces:
    # - name: source
    #- name: basic-auth
  params:
    - name: repo_url
    - name: revision
  tasks:
    - name: task-spec
      taskSpec:
        steps:
          - name: task-spec
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: |
              #!/usr/bin/env bash
              command_not_found

    - name: task-failure2
      taskSpec:
        steps:
          - name: task-failure2
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: |
              #!/usr/bin/env bash
              hello_another_failure

    - name: task-referenced-internally
      taskRef:
        name: task-referenced-internally

    # - name: git-clone-from-catalog
    #   taskRef:
    #     name: git-clone
    #   params:
    #     - name: url
    #       value: $(params.repo_url)
    #     - name: revision
    #       value: $(params.revision)
    #workspaces:
        # - name: output
        #   workspace: source
        #- name: basic-auth
        #      workspace: basic-auth
