---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scratchmyback-pull-request
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                ls /xxx
