---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-1
      image: gcr.io/distroless/python3:nonroot
      script: |
        #!/usr/bin/python3
        print("Hello task1")
