---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: foo
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/foo.*"
spec:
  pipelineSpec:
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                cat <<EOF
                Custom Param is: {{ custom }}
                EOF
