---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: update-branch
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/update"
spec:
  pipelineSpec:
    tasks:
      - name: update-branch
        displayName: Update pull request with main
        taskSpec:
          steps:
            - name: update
              image: registry.access.redhat.com/ubi9/ubi-minimal
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "{{ git_auth_secret }}"
                      key: "git-provider-token"
              script: |
                curl -L \
                  -X PATCH \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/pulls/{{ pull_request_number }} \
                  -d '{"title":"new title","body":"updated body","state":"open","base":"main"}'
